### ISSUE TITLE
[RFE] Sendgrid (or other API email service)

### ISSUE THREAD

**Issue by christianh814** [OpenShiftDemos/gogs-openshift-docker#2]
Usually for other apps (including gitlab and wordpress) I just need to provide the following...

smtp.sendgrid.net:587
sendgridusername
sendgridpassword

1) Not sure if Gogs can use sendgrid
2) If so...these should be able to be set as env variables or in the ini file

**Comment by thoraxe** [comment]
During the installation there is a tab at the bottom to expand to include the smtp information. 

You could also extract the app.ini before putting it into the configmap and then add it. 

Unfortunately the golang ini implementation doesn't appear to be able to use environment variables, as best I can tell. If it could you could use a template. If it can I can't tell how.

**Comment by thoraxe** [comment]
If you can figure out how to use environment variables with golang ini we can reopen this but for now there's not a hard requirement on email so I'll just close.
