### ISSUE TITLE
Infinate ContainerCreating after configmap setup

### ISSUE THREAD

**Issue by christianh814** [OpenShiftDemos/gogs-openshift-docker#3]
After adding the configmap via a volume to the `dc`...

```
oc volume dc/gogs --add --name=config-volume -m /etc/gogs/conf/ --source='{"configMap":{"name":"config-volume","items":[{"key":"appini","path":"app.ini"}]}}
```

The pod stays in a "ContianerCreating" state

```
[root@ose3-master ~]# oc get pods
NAME                 READY     STATUS              RESTARTS   AGE
gogs-1-hlut3         1/1       Running             0          26m
gogs-2-91275         0/1       ContainerCreating   0          5m
gogs-2-deploy        1/1       Running             0          5m
postgresql-1-n767j   1/1       Running             3          30m
```

Found this on the node that's being scheduled

```
May 24 16:07:17 ose3-node2.example.com atomic-openshift-node[2474]: E0524 16:07:17.915440    2474 kubelet.go:1796] Unable to mount volumes for pod "gogs-2-91275_infra(3c2d0709-2204-11e6-843d-525400daa840)": conf
```

**Comment by thoraxe** [comment]
I'm not really sure on this one. Can you do "oc get event"  in the project?

**Comment by christianh814** [comment]
Looks like I misunderstood the `config-volume` part...I took it as a literal. I got it working by doing...

`oc volume dc/gogs --add --name=gogs -m /etc/gogs/conf/ --source='{"configMap":{"name":"gogs","items":[{"key":"appini","path":"app.ini"}]}}'`

**Comment by thoraxe** [comment]
I don't see a difference. It should have worked with "config-volume". I'll go through it again myself just to double check. 

I assume you're using 3.2 for OpenShift and your oc client?
