### ISSUE TITLE
README update

### ISSUE THREAD

**Issue by willemvd** [OpenShiftDemos/gogs-openshift-docker#8]
- In the README there are instructions to setup PostgreSQL yourself, but in the latest openshift-template there is a PostgreSQL created.
- The README also points to a gogs.yaml but this should be the openshift-template.yaml I guess
- Are the more things changed? Maybe the stuff around using the ConfigMap? There is also a gogs-data PersistentVolumeClaim so is that still needed?

**Comment by rafaeltuelho** [comment]
Also please add a note about the admin Gogs user. As described in GOGs' official FAQ [1]:

> Administration
> 
> How can I become an administrator?
> 
> The first registered user with ID = 1 is an administrator. No e-mail confirmation is required for this (if enabled). > The default administrator can log into Admin > Users and authorize another user. A user will also be an > administrator if they register in the install page.

[1] https://gogs.io/docs/intro/faqs

**Comment by thoraxe** [comment]
Please feel free to submit PRs.

**Comment by hodrigohamalho** [comment]
Please merge the PR.
I just went trough the same problem about credentials.

**Comment by siamaksade** [comment]
Merged
